apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supporting-material-manager.configMapName" . }}
  labels:
    {{- include "supporting-material-manager.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.config.APP_PORT | quote }}
  MINIO_URL: {{ default (printf "%s-service" (include "supporting-material-manager.minioName" .)) .Values.config.MINIO_URL | quote }}
  MINIO_PORT: {{ .Values.config.MINIO_PORT | quote }}
  FHIR_URL: {{ .Values.config.FHIR_URL | quote }}
  GH_BUCKET: {{ .Values.config.GH_BUCKET | quote }}
  API_URL: {{ .Values.config.API_URL | quote }}
