apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supporting-material-manager.secretName" . }}
  labels:
    {{- include "supporting-material-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  minio.root.user: {{ .Values.secret.minioRootUser | quote }}
  minio.root.password: {{ .Values.secret.minioRootPassword | quote }}
